version: "3.8"

services:
  payments-mongo:
    image: mongo:4.0.4
    container_name: payments-mongo
    restart: on-failure
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/payments:/data/db
    networks:
      - parking_network

  payments-service:
    image: perkzen/parking-app-payments-service
    ports:
      - "8081:8080"
      - "9000:9000"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:root@payments-mongo:27017
    depends_on:
      - payments-mongo
    networks:
      - parking_network

  cars-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parking_app_db
    networks:
      - parking_network

  cars-service:
    image: perkzen/parking-app-cars-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cars-db:5432/parking_app_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRINGDOC_SWAGGER_UI_PATH: /docs
    depends_on:
        - cars-db

  mobile-api-gateway:
    image: perkzen/parking-app-mobile-api-gateway
    ports:
      - "8083:8080"
    environment:
      - CAR_SERVICE_URL=http://cars-service:8082
      - PAYMENT_SERVICE_GRPC_URL=payments-service:9000
      - PAYMENT_SERVICE_URL=http://payments-service:8081
    networks:
      - parking_network
    depends_on:
      - cars-service
      - payments-service

networks:
  parking_network:
    driver: bridge
